# Generated by Django 3.2.25 on 2024-08-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll_details',
            name='date',
        ),
    ]
